version: '3.1'

services:
  pgsql:
    container_name: jony_super_db
    image: postgres:latest
    ports:
      - "5431:5432"
    volumes:
      - "./var/db:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: hey_jony
      POSTGRES_USER: jony
      POSTGRES_PASSWORD: genius
